# docker-compose.yml 예
version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: aawga-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_data:
