openapi: 3.0.3
info:
  title: AAWGA Agent API
  version: 1.0.0

paths:
  /requirements:
    post:
      summary: "사업계획서에서 요구사항 추출"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RequirementAgentInput'
            examples:
              sample-upload:
                summary: "사업계획서 파일 업로드 예시"
                value:
                  business_plan: "(binary plan.pptx)"
      responses:
        '200':
          description: "추출된 요구사항 리스트"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequirementDefinition'
              examples:
                success:
                  summary: "요구사항 추출 성공 예시"
                  value:
                    requirements:
                      - id: "REQ-001"
                        title: "유저 로그인 기능"
                        description: "이메일/비밀번호를 통한 로그인 지원"
                        priority: "High"
                      - id: "REQ-002"
                        title: "회원가입 기능"
                        description: "이메일 기반 회원가입 및 OAuth 소셜 로그인 지원"
                        priority: "Medium"

components:
  schemas:
    RequirementAgentInput:
      $ref: './schemas/requirement_agent_input.json'
    RequirementDefinition:
      $ref: './schemas/requirement_agent_output.json'
