openapi: 3.0.3
info:
  title: AAWGA Agent API
  version: 1.0.0

paths:
  /requirements:
    # ... (기존 정의 생략)

  /testcases:
    # ... (기존 정의 생략)

  /traceability:
    post:
      summary: "요구사항 및 테스트케이스로부터 추적성 매트릭스 생성"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TraceabilityAgentInput'
            examples:
              sample-input:
                summary: "요구사항 및 테스트케이스 샘플"
                value:
                  requirements:
                    - id: "REQ-001"
                      title: "유저 로그인 기능"
                      description: "이메일/비밀번호 로그인 지원"
                      priority: "High"
                    - id: "REQ-002"
                      title: "회원가입 기능"
                      description: "이메일·소셜 로그인 지원"
                      priority: "Medium"
                  testcases:
                    - id: "TC-001"
                      requirement_id: "REQ-001"
                      steps:
                        - "로그인 페이지 열기"
                        - "정보 입력"
                        - "로그인 버튼 클릭"
                      expected_result: "대시보드로 이동"
                    - id: "TC-002"
                      requirement_id: "REQ-002"
                      steps:
                        - "회원가입 페이지 열기"
                        - "정보 입력"
                        - "가입 완료"
                      expected_result: "회원가입 성공 메시지"

      responses:
        '200':
          description: "생성된 추적성 매트릭스"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TraceabilityDefinition'
              examples:
                success:
                  summary: "추적성 매트릭스 예시"
                  value:
                    traceability_matrix:
                      - requirement_id: "REQ-001"
                        testcase_ids:
                          - "TC-001"
                      - requirement_id: "REQ-002"
                        testcase_ids:
                          - "TC-002"

components:
  schemas:
    RequirementAgentInput:
      $ref: './schemas/requirement_agent_input.json'
    RequirementDefinition:
      $ref: './schemas/requirement_agent_output.json'
    TestcaseAgentInput:
      $ref: './schemas/testcase_agent_input.json'
    TestcaseDefinition:
      $ref: './schemas/testcase_agent_output.json'
    TraceabilityAgentInput:
      $ref: './schemas/traceability_agent_input.json'
    TraceabilityDefinition:
      $ref: './schemas/traceability_agent_output.json'
