openapi: 3.0.3
info:
  title: AAWGA Agent API
  version: 1.0.0

paths:
  /requirements:
    post:
      summary: "사업계획서에서 요구사항 추출"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RequirementAgentInput'
      responses:
        '200':
          description: "추출된 요구사항 리스트"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequirementDefinition'

components:
  schemas:
    RequirementAgentInput:
      $ref: './schemas/requirement_agent_input.json'
    RequirementDefinition:
      $ref: './schemas/requirement_agent_output.json'
