name: AAWGA CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        working-directory: AAWGA      # ← 추가
        run: pip install -r requirements.txt

      - name: Start FastAPI server
        working-directory: AAWGA
        run: |
          nohup uvicorn backend.app:app --host 127.0.0.1 --port 8000 --reload > uvicorn.log 2>&1 &
          sleep 5

      - name: Run tests with pytest
        working-directory: AAWGA      # ← 이미 설정되어 있습니다
        run: pytest --maxfail=1 --disable-warnings -q
