name: AAWGA CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r AAWGA/requirements.txt

      - name: Start FastAPI server
        working-directory: AAWGA
        run: |
          # 백그라운드로 서버 실행
          nohup uvicorn backend.app:app --host 127.0.0.1 --port 8000 --reload > server.log 2>&1 &
          # 서버가 기동될 때까지 대기 (필요 시 시간 조절)
          sleep 5

      - name: Run tests with pytest
        working-directory: AAWGA
        run: pytest --maxfail=1 --disable-warnings -q
