name: Scaffold AAWGA Structure

# 수동 트리거
on:
  workflow_dispatch:

# 리포지토리 컨텐츠 수정·푸시를 위한 권한 부여
permissions:
  contents: write

jobs:
  scaffold:
    runs-on: ubuntu-latest

    steps:
      # 레파지토리 체크아웃 (토큰 유지)
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 폴더·파일 생성 (이미 존재하면 스킵)
      - name: Create directory structure
        run: |
          # 디렉터리 생성 (기존에도 idempotent)
          mkdir -p AAWGA/.github/workflows
          mkdir -p AAWGA/docs
          mkdir -p AAWGA/streamlit_app/pages
          mkdir -p AAWGA/streamlit_app/components
          mkdir -p AAWGA/streamlit_app/utils
          mkdir -p AAWGA/backend/routers
          mkdir -p AAWGA/backend/services
          mkdir -p AAWGA/agents
          mkdir -p AAWGA/models
          mkdir -p AAWGA/scripts
          mkdir -p AAWGA/tests

          # 파일 생성: 없을 때만 touch
          for file in \
            AAWGA/.github/workflows/ci.yml \
            AAWGA/docs/architecture.md \
            AAWGA/docs/requirements.md \
            AAWGA/docs/usage.md \
            AAWGA/streamlit_app/main.py \
            AAWGA/streamlit_app/pages/home.py \
            AAWGA/streamlit_app/pages/upload.py \
            AAWGA/streamlit_app/pages/feedback.py \
            AAWGA/streamlit_app/components/logo.py \
            AAWGA/streamlit_app/utils/spec_loader.py \
            AAWGA/backend/app.py \
            AAWGA/backend/routers/requirements.py \
            AAWGA/backend/routers/testcases.py \
            AAWGA/backend/routers/traceability.py \
            AAWGA/backend/services/rag_search.py \
            AAWGA/agents/base_agent.py \
            AAWGA/agents/requirement_agent.py \
            AAWGA/agents/testcase_agent.py \
            AAWGA/agents/traceability_agent.py \
            AAWGA/models/schemas.py \
            AAWGA/models/db_models.py \
            AAWGA/scripts/deploy.sh \
            AAWGA/scripts/docker_build.sh \
            AAWGA/tests/test_streamlit.py \
            AAWGA/tests/test_api.py \
            AAWGA/tests/test_agents.py \
            AAWGA/.env.example \
            AAWGA/.gitignore \
            AAWGA/Dockerfile \
            AAWGA/requirements.txt \
            AAWGA/README.md; do
            if [ ! -f "$file" ]; then
              touch "$file"
              echo "Created $file"
            fi
          done

      # 변경 커밋 & 메인 브랜치에 푸시 (새 파일이 있을 때만)
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # 변경된 파일이 있을 경우에만 커밋
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Scaffold: add missing repo structure"
            git push
          else
            echo "No changes to commit."
          fi